# Generated by Django 3.2.6 on 2021-08-02 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=8)),
                ('servings', models.CharField(max_length=3)),
                ('ingridients', models.TextField()),
                ('desc', models.TextField()),
                ('cuisine', models.CharField(choices=[('', 'Choose one'), ('tr', 'Traditional'), ('vt', 'Vegetarian'), ('ve', 'Vegan')], default='', max_length=2)),
                ('level', models.CharField(choices=[('', 'Choose one'), ('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], default='', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
